server:
  port: 9000
---
spring:
 server:
  port: 9000
---
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
 
    gateway:
      routes:
        - id: uaa
          uri: http://localhost:8081/
          predicates:
            - Path=/api-uaa/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: auth-login-process
          uri: lb://uaa
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: auth-login-token
          uri: http://localhost:8080/
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: auth-login-authorize
          uri: http://localhost:8080/
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
        - id: auth-check-process
          uri: http://localhost:8080/
          predicates:
            - Path=/check_token
          filters:
            - PreserveHostHeader
        - id: order
          uri: http://localhost:8003/
          predicates:
            - Path=/getOrder
          filters:
            - PreserveHostHeader
---
server:
  port: 8080
  spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    ---
    server:
  port: 8003
spring:
  application:
    name: order
redis:
    host: 127.0.0.1
    port: 6379
